### ISSUE TITLE
Fatal error when phpunit 9 generate html coverage

### ISSUE THREAD

**Issue by roquie** [amphp/windows-registry#2]
Please, don't use symbolic links in packages ...
https://github.com/sebastianbergmann/php-file-iterator/issues/67 

`amphp/windows-registry: v0.3.2`

**Comment by trowski** [comment]
Symbolic links in packages are not unusual. Tools should support symbolic links. Bugs regarding handling of symbolic links should be reported (as you have) and fixed, rather than a reason to remove symbolic links from packages.

**Comment by kelunik** [comment]
Fixed in v0.3.3.

**Comment by trowski** [comment]
Note this was due to the `docs` directory being exported in composer installs. @roquie Please be more detailed in your future bug reports so I can better understand the issue at hand.
